version: '3'
services:
  my_postgres:
    image: postgres:latest
    container_name: bend-backend-task
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bend-backend-task
volumes:
  pgdata:
    driver: local